### ISSUE TITLE
iQontrol

### ISSUE THREAD

**Issue by sbormann** [ioBroker/plugin-sentry#18]
Please add iQontrol to sentry

https://github.com/sbormann/ioBroker.iqontrol

Many thanks and greetings!

**Comment by Apollon77** [comment]
Willst Du das für Serverside oder Web-Teil? Wenn Web was ist es für Tech? Oder willste beides?
Sentry Zugriff hast Du generell schon?

**Comment by sbormann** [comment]
Hi Ingo,
mach für beides Sinn, oder? Habe noch nie mit Sentry gearbeitet und wollte mich mal rantasten. Was denkst Du? Der Web-Teil ist pures JS (mit jQuery).
LG

Von: Ingo Fischer <notifications@github.com>
Gesendet: Donnerstag, 30. Juli 2020 12:17
An: ioBroker/plugin-sentry <plugin-sentry@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/plugin-sentry] iQontrol (#18)


Willst Du das für Serverside oder Web-Teil? Wenn Web was ist es für Tech? Oder willste beides?
Sentry Zugriff hast Du generell schon?

**Comment by Apollon77** [comment]
Also wie du magst. Es hat sich als sinnvoll rausgestellt das in getrennten Projekten zu machen. Und das in JQuery musst DU manuell einbauen ... der controller kann nur das für die Server Seite.
Am besten kontaktiere mich erstmal im Telegram (hast du?) wegen generellem Sentry Zugriff

**Comment by sbormann** [comment]
Hi, verstehe. Dann mache ich erst mal Server Seite. Meine Telegram-Nummer ist +49 177 7921169. Danke und VG!

Von: Ingo Fischer <notifications@github.com>
Gesendet: Donnerstag, 30. Juli 2020 23:37
An: ioBroker/plugin-sentry <plugin-sentry@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/plugin-sentry] iQontrol (#18)


Also wie du magst. Es hat sich als sinnvoll rausgestellt das in getrennten Projekten zu machen. Und das in JQuery musst DU manuell einbauen ... der controller kann nur das für die Server Seite.
Am besten kontaktiere mich erstmal im Telegram (hast du?) wegen generellem Sentry Zugriff
