### ISSUE TITLE
Please add https://github.com/Mic-M/ioBroker.smartcontrol

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/plugin-sentry#19]
https://github.com/Mic-M/ioBroker.smartcontrol

Thanks.

**Comment by Apollon77** [comment]
WIllst Du das für Server sie und zweites Projekt für den JS Teil? Wenn ja was ist das für eine Technologie?

**Comment by Apollon77** [comment]
nodejs done

**Comment by Mic-M** [comment]
Danke. Es gibt im Prinzip nur eine "Server-Seite", also kein Web-Frontend, außer die Admin-Konfig. Daher nur Serverseitig...
