### ISSUE TITLE
Please add nsclient

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/plugin-sentry#191]
Please add adapter nsclient:

https://github.com/iobroker-community-adapters/ioBroker.nsclient

**Comment by mcm1957** [comment]
I go with sentry.io for the moment

**Comment by Apollon77** [comment]
But why? :-)

**Comment by mcm1957** [comment]
Hatte 
Den Eindruck 
Ihr wollt keine neuen Adapter.
Immerhin sind die letzten Request aus 2021 u ein Request ohn weitere Remsrks seit 2021 offen.

Ainnvoller erschiene mir ein Eintrag im iob sentry. Aber ich kann mit beidem leben :-).

Lasst mich wissen was gewunschen ist

**Comment by mcm1957** [comment]
Und ja
Das prov sentry hat auch nachteile. 
Weil github binding geht dann wieder micht weil rechte im repo fehlen ....

**Comment by Apollon77** [comment]
Falscher eindruck ... kein Problem hinzuzufügen. Und repo recht kann man einmalig geben (da erhöhe ich deine rechte das du das kannst falls nicht communty - da darf sentry schon ... Also reopen wenn du magst. kein problem

Das eine ofene hat einen grund ... der Dev ist inzwischen inaktiv ... und ich vergebe Sentry nur wenn auch jemand die issues bearbeitet, sonst ists Datenmüll

**Comment by mcm1957** [comment]
I would request to add an project entry for nsclient to the iobroker sentry server if possible.

**Comment by mcm1957** [comment]
@Apollon77 
non prio reminder.
Hoff ich bin nicht lästig

**Comment by Apollon77** [comment]
wow ... yes completely forgot ... sorry ... will take care tomorrow

**Comment by Apollon77** [comment]
dsn: "https://88c5966010c140a0a0fdf4239c5fbffc@sentry.iobroker.net/217",

**Comment by mcm1957** [comment]
Thanks
