### ISSUE TITLE
Add the lightcontrol to Sentry

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/plugin-sentry#202]
Please add the adapter lightcontrol to Sentry
[https://github.com/Schmakus/ioBroker.lightcontrol.git](https://github.com/Schmakus/ioBroker.lightcontrol.git)

**Comment by Apollon77** [comment]
Bitte schreibe mich im Telegram oder Discord an, ich brauche eine E-mail für Sentry freischaltung ... und dann kan es nach dem Adapter-Review fürs Repo weiter gehen
