### ISSUE TITLE
Please add fully-mqtt to Sentry

### ISSUE THREAD

**Issue by Acgua** [ioBroker/plugin-sentry#213]
Can you please add https://github.com/Acgua/ioBroker.fully-mqtt to Sentry.
I have provided my email address to Apollon via ioBroker Forum Chat.
Thanks.

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key

**Comment by mcm1957** [comment]
@Apollon77 - ping, adapters are waiting for an sentry key

**Comment by mcm1957** [comment]
@Apollon77 
This adapter has been deprecated.
https://github.com/Acgua/ioBroker.fully-mqtt/issues/52

**So this issue can be closed.**
