### ISSUE TITLE
Frage zur Diskussion: Loglevel für 'Plugin sentry Initialize Plugin (enabled=true)'

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/plugin-sentry#22]
Hi,

ich habe dank Ingo nun Sentry in 3 Adaptern integriert.

Bei Adapter-Start steht folgendes im Log:
`
smartcontrol.1 | 2020-07-30 23:35:50.312 | debug | (6593) Plugin sentry Initialize Plugin (enabled=true)
`

Ich persönlich bin bezüglich Datenschutz relativ schmerzfrei, aber manche User sind da extrem vorsichtig.
Wie wäre es also mit:
1. Umstellung auf Info-Loglevel aus Transparenz-Gründen
2. Erweiterter Logausgabe-Text: `Anonymous Sentry Error Reporting enabled. Details, incl. deactivation instructions: https://github.com/ioBroker/plugin-sentry`

Nicht dass hier mal ein übermotivierter Datenschützer auf ioBroker losgeht.

Zusätzlich hab ich jetzt mal im SmartControl folgenden Hinweis ergänzt.
https://github.com/Mic-M/ioBroker.smartcontrol#sentry-error-reporting

Was meint ihr?

**Comment by Apollon77** [comment]
Das Thema am Info Logging ist das es bei jedem Start kommt - vor allem bei Scheduled Adapter kann das oft sein und die User bei anderen Dingen schon meckern wenn zuviel als "Info geloggt wird ;-) Daher kam es nicht per info. Kann man aber natürlich diskutieren.

Sonst kommt die Sentry Info das es aktiviert ist bei einer installation von ioBroker oder einem Upgrade auf die 3.1.x und es steht in den T&Cs die beider Installation abgeklickt werden.

In der Sentry Anleitung steht auch das jeder Dev der es in einen Adapter einbaut den folgenden Satz in die Readme aufnehmen muss (haben wir gemacht damit es kein eigener Abschnitt sein muss wie Du es gemacht hast :-)

```
**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.
```

**Comment by Mic-M** [comment]
Danke, dann ergibt auch das Debug Level Sinn, also gerade bei Adapter-Neustarts etc. Schön, dass hier schon so viele Gedanken eingeflossen sind :-)

Den Hinweis "You add (...) and a short info section to your README Readme add to top please" hab ich glatt übersehen, umso besser ;)

Ich denke, damit kann man das hier schließen.

**Comment by Apollon77** [comment]
Aber danke fürs aufbringen.
