### ISSUE TITLE
Please add community adapter Iceroad

### ISSUE THREAD

**Issue by ciddi89** [ioBroker/plugin-sentry#220]
Hi @Apollon77 

it would be nice if we can add the community adapter iceroad - https://github.com/iobroker-community-adapters/ioBroker.iceroad

If something must be changed you can contact me as maintainer. 

Thanks

**Comment by ciddi89** [comment]
@Apollon77 knock knock :)

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key
