### ISSUE TITLE
Please add device-watcher to sentry

### ISSUE THREAD

**Issue by ciddi89** [ioBroker/plugin-sentry#226]
Hi @Apollon77

it would be nice if we can add the adapter device-watcher - https://github.com/ciddi89/ioBroker.device-watcher

If something must be changed you can contact me as maintainer.

Thanks

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for an sentry key
