### ISSUE TITLE
please add https://github.com/HGlab01/ioBroker.followthesun

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/plugin-sentry#26]
Please add
https://github.com/HGlab01/ioBroker.followthesun

Thanks a lot!

**Comment by HGlab01** [comment]
Hi @Apollon77 and @AlCalzone! 
Any chance to get sentry access?

**Comment by Apollon77** [comment]
Please contact me in Telegram or Discord or via email and send me an email-address  for access to sentry. YOu also need a 2FA app like Google Authenticator
