### ISSUE TITLE
Ignore "no space left on device" errors

### ISSUE THREAD

**Issue by klein0r** [ioBroker/plugin-sentry#27]
There is no need to push those to sentry

**Comment by Apollon77** [comment]
They should be excluded already when newest plugin is used https://github.com/ioBroker/plugin-sentry/blob/master/index.js#L160 ... so eighter this do not work or the users do not have the uptodate lib ... normally 1.1.4 as dp was in js.controller 3.1.6 ... so it migth now work as expected ... grmpf ... nee do check why ... this is hard to reproduce :-(

**Comment by klein0r** [comment]
Thank you, the issue was created because of this sentry report:
https://sentry.iobroker.net/organizations/iobroker/issues/6296/

- jsControllerVersion 3.1.6
- nodejsVersion v14.15.1

**Comment by Apollon77** [comment]
shpuld be fixed with 1.1.5 of the plugin-sentry ... should be used for new installations, especially with controller 3.2 ...
