### ISSUE TITLE
Please add iobroker.meteoalarm and iobroker.countdown

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/plugin-sentry#52]
Please added meteoalarm and countdown
Github: 
https://github.com/jack-blackson/ioBroker.meteoalarm
https://github.com/jack-blackson/ioBroker.countdown

thx jack

**Comment by Apollon77** [comment]
Are you in Telegram? Or discord? Please send me a message there with your email for sentry invitation

**Comment by jack-blackson** [comment]
I dropped you a message on discord.
