### ISSUE TITLE
Please create an DSN for ioBroker.kecontact

### ISSUE THREAD

**Issue by Sneak-L8** [ioBroker/plugin-sentry#69]
Can you please provide a DSN for the adapter [ioBroker.kecontact](https://github.com/Sneak-L8/ioBroker.kecontact)?

Access rights are only needed for myself.

**Comment by Apollon77** [comment]
Are you rlaos in Discord or Telegram? if yes write me there please.I need an email for Sentry invitation and would add you also in the Sentry groups there

**Comment by Sneak-L8** [comment]
No, I'm Sneak-L8, git@sengler.de, not yet at discord, but will join then also.

**Comment by Sneak-L8** [comment]
Even when hitting "resend activation mail" multiple times, no email is received....

**Comment by Sneak-L8** [comment]
Perhaps same problem in other systems? Is discord still sending mails without? My hoster requires TLS for mail delivery...

**Comment by Apollon77** [comment]
On Discord ...noidea ... but Iwould expect them tosend correct mails :-(
Maybe write in forum. I will send youan Sentry invito to this email too

**Comment by Apollon77** [comment]
dsn: "https://01d409e4ecea470485101a0f53720ee5@sentry.iobroker.net/139",
