### ISSUE TITLE
The usual "...registered" messages have disappeared now for some days while saving scripts

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/plugin-sentry#78]
**Describe the bug**  
I am used to seeing the "...registered" messages while saving scripts (Blockly et. al). This shows me that a condition for a change on a data point has been registered and when the change happens the code is being executed.

**To Reproduce**  
I can save changed scripts but do not see any messages any more.
I disabled sentry in the javascript.0 instance and set the log level to silly: I get more messages while and after saving the script but not the "...registered" messages.

**Expected behavior**  
The "...registered" messages etc are shonw below the script source window.

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: 5.2.8

**Additional context**  
-

**Comment by MichaelSchaaf999** [comment]
I changed the log lvel now to "info" ind even activated sentry again: Now I can see the missing messages in the window below the script window. Only difference: A schedule (Cron rule) within a actualisation registration (subscription: Falls Objekt... wurde aktualisiert...) is not counted: 

10:06:39.266 | info | javascript.0 (25073) script.js.Automatisierungen.nach_Tageszeit.SchlZi_Lichter_an:_Wecker: registered 1 subscription and **0 schedules**
-- | -- | --
But there is a schedule within the subscription.

**Comment by Apollon77** [comment]
I think you want to create that isue in the iobroker.javascript repo, or ?!

The referenced log message is generated by javascript adapter when the script is started!
